name: Packaging the react project
on: push

permissions:
  contents: write

jobs:
  npm-build:
    name: npm-build work
    runs-on: ubuntu-latest

    steps:
    - name: Read the contents of the repository
      uses: actions/checkout@v4

    - name: Installation of dependencies and project packaging
      run: |
        npm install
        npm run build

    -name: deploy
     uses: JamesIves/github-pages-deploy-action@v4
     with: 
       branch: gh-pages  
       folder: build

    





















